### ISSUE TITLE
SimpleText获取了整个textview的点击却只处理了部分的点击事件

### ISSUE THREAD

**Issue by DanteAndroid** [jaychang0917/SimpleText#1]
我使用SimpleText将textView的部分文字『变蓝』并且添加点击事件。很好用。但是我点击蓝字以外的部分，却并没有触发点击事件~有没有办法处理蓝字外部区域的点击事件呢（比如点击后回复，这也是很常见的功能），谢谢

**Comment by jaychang0917** [comment]
then i think you can set a click listener for the textview.

**Comment by DanteAndroid** [comment]
Works well. Thanks I'm so reckless

**Comment by DanteAndroid** [comment]
@jaychang0917 I'm sorry, but the click event happens twice when I click matched text in simpleText, how I deal with that?
