### ISSUE TITLE
onClick is too sensitive

### ISSUE THREAD

**Issue by azri92** [jaychang0917/SimpleText#8]
Hi,

The `onClick` method seems to be too sensitive. Even when scrolling/dragging, if user happens to touch the linked text, it will activate the listener. To compare, you can try dragging on top of a normal button widget & it will not fire (since it's a drag, not a click).

I'm not sure if this is Android's problem with onTextClickedListener, but maybe you can take a look.

Thanks!

**Comment by jaychang0917** [comment]
Version `2.0.1` fixed the issue.
